language: python
python:
  - "3.8.1"
install:
  - pip install -r requirements.txt
script:
  - python3 setup.py test
env:
  - CODECOV_TOKEN=50e4ba85-a1ee-496c-8c90-2eb23a257b82
after_success:
  - codecov