language: python
python:
  - "3.8.1"
install:
  - pip install -r requirements.txt
script:
  - python3 setup.py test
env:
  - CODECOV_TOKEN=6d67d79c-93c1-4c01-9447-f1ac20d2d884
after_success:
  - codecov