version: "3"

services:
# commented for testing

  postgres:
    image: postgres:latest
    volumes:
      - "postgres_data:/var/lib/postgres"
    networks:
      - postgres-net
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: admin
      POSTRGRES_PASSWORD: admin
    restart: always

  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - postgres-net
    environment:
      - postgres_host=lms_postgres_1

volumes:
  postgres_data:

networks:
  postgres-net:
